name: Run unit tests

on:
  workflow_dispatch:
  push:
    branches: '**'

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v6
    - uses: actions/setup-node@v6
      with:
        node-version: '24'
        cache: npm
        cache-dependency-path: ./package-lock.json
    - name: Install dependencies
      run: npm install
    - name: Run unit tests
      run: npm test
    - name: Run type checks
      run: npm run typecheck
